<a href="https://colab.research.google.com/github/Santhoshkumar5655/datasciencelearning/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
!pip install numpy

In [12]:
import numpy as np
#1d array
l = [1,2,3,4,5]
print(l)
print("type of list", type(l))
#after converting into list
l = np.array(l)
print(l)
print("type of array", type(l))
print(l.ndim)

[1, 2, 3, 4, 5]
type of list <class 'list'>
[1 2 3 4 5]
type of array <class 'numpy.ndarray'>
1


In [13]:
#creating 2d arrays
l1 = [1,2,3,4,5]
l2 = [3,4,5,6,7]
l3 = [5,6,7,8,9]
l4 = np.array([
    l1,
    l2,
    l3
])
print(l4)
print(l4.ndim)

[[1 2 3 4 5]
 [3 4 5 6 7]
 [5 6 7 8 9]]
2


In [14]:
l1 = [
 [1,2],
 [3,4]
]
l2 = [
 [1,2],
 [3,4]
]
l3 = np.array([
    l1,l2
])
print(l3)
print(l3.ndim)

[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]
3


In [15]:
# Different Ways to Create Arrays in NumPy

In [16]:
#using array
l = [1,2,3,4,5]
p = (1,2,3,4,5)
l = np.array(l)
p = np.array(p)
print("list converted into array")
print(l)
print("tuple converted into array")
print(p)

list converted into array
[1 2 3 4 5]
tuple converted into array
[1 2 3 4 5]


In [17]:
#fromiter
l = [1,2,3,4,5]
arr = np.fromiter(l, dtype=int)
print(arr)

[1 2 3 4 5]


In [18]:
#arange
l = np.arange(5)
print(l)
l = np.arange(1,9)
print(l)
l = np.arange(1,10,2)
print(l)


[0 1 2 3 4]
[1 2 3 4 5 6 7 8]
[1 3 5 7 9]


In [19]:
arr = np.linspace(1,5,100)
print(arr)

[1.         1.04040404 1.08080808 1.12121212 1.16161616 1.2020202
 1.24242424 1.28282828 1.32323232 1.36363636 1.4040404  1.44444444
 1.48484848 1.52525253 1.56565657 1.60606061 1.64646465 1.68686869
 1.72727273 1.76767677 1.80808081 1.84848485 1.88888889 1.92929293
 1.96969697 2.01010101 2.05050505 2.09090909 2.13131313 2.17171717
 2.21212121 2.25252525 2.29292929 2.33333333 2.37373737 2.41414141
 2.45454545 2.49494949 2.53535354 2.57575758 2.61616162 2.65656566
 2.6969697  2.73737374 2.77777778 2.81818182 2.85858586 2.8989899
 2.93939394 2.97979798 3.02020202 3.06060606 3.1010101  3.14141414
 3.18181818 3.22222222 3.26262626 3.3030303  3.34343434 3.38383838
 3.42424242 3.46464646 3.50505051 3.54545455 3.58585859 3.62626263
 3.66666667 3.70707071 3.74747475 3.78787879 3.82828283 3.86868687
 3.90909091 3.94949495 3.98989899 4.03030303 4.07070707 4.11111111
 4.15151515 4.19191919 4.23232323 4.27272727 4.31313131 4.35353535
 4.39393939 4.43434343 4.47474747 4.51515152 4.55555556 4.595959

In [20]:
arr = np.empty((5,3))
print(arr)

[[5.28764121e-315 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 6.89309113e-310 1.50008929e+248]
 [4.31174539e-096 9.80058441e+252 1.23971686e+224]
 [1.05118785e-153 9.03292329e+271 9.08366793e+223]
 [1.06244660e-153 3.44981369e+175 6.32404027e-322]]


In [21]:
arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


zeros and ones we will us in the deep learning tech

In [22]:
arr = np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [23]:
arr = np.array([[1,2,3,4,5],[4,5,6,7,8]])
print(arr)
print(arr.shape) # if we want to know the number of rows and columns we will use this shape property
print(arr.ndim) # if we want to know the dimension of an array we will use ndim property
print(arr.dtype) # if we want to know the datatype of an array we will use dtype property

[[1 2 3 4 5]
 [4 5 6 7 8]]
(2, 5)
2
int64


In [24]:
arr = np.array([[1,2,3,4,5],[4,5,6,7,8]])
print(arr)
print(arr.sum(axis =0))
print(arr.sum(axis =1))

[[1 2 3 4 5]
 [4 5 6 7 8]]
[ 5  7  9 11 13]
[15 30]


In [25]:
#indexing
l = [10,20,30,40]
arr = np.array(l)
print(arr[3])
print(arr[0])
print(arr[1])
print(arr[-1])

40
10
20
40


In [26]:
l2 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(l2)
print(l2[0,0])
print(l2[2,2])
print(l2[1,0])
print(l2[0])
print(l2[1])
print(l2[2])
print(l2[:,0])
print(l2[:,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
9
4
[1 2 3]
[4 5 6]
[7 8 9]
[1 4 7]
[2 5 8]


In [27]:
# l[start:end:step]
l = [1,2,3,4,5]
arr = np.array(l)
print(arr)
print(arr[0:2])
print(arr[0:5])
print(arr[1:5])
print(arr[0:5:2])
print(arr[1:])
print(arr[:4])

[1 2 3 4 5]
[1 2]
[1 2 3 4 5]
[2 3 4 5]
[1 3 5]
[2 3 4 5]
[1 2 3 4]


In [28]:
# l[row_start:row_end, col_start:col_end]
l = np.array([
    [1,2,3,4],
    [4,5,6,7],
    [8,9,10,11]
])
print(l)
print(l[0:2,0:2])

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1 2]
 [4 5]]


In [29]:
#reshaping : changing an array from one dimension to another dimension
l = [1,2,3,4,5,6]
l = np.array(l)
print(l)
print(l.ndim)
new_arr = l.reshape(2,3)
print(new_arr)
print(new_arr.ndim)

[1 2 3 4 5 6]
1
[[1 2 3]
 [4 5 6]]
2


In [30]:
arr = np.array([1,2,3,4,5])
arr.resize(2,3)
print(arr)

[[1 2 3]
 [4 5 0]]


In [32]:
import numpy as np

In [33]:
arr1 = np.array([1,2,3])
arr2 = np.array([10,20,30])
print(arr1+arr2)
#subtraction
# 10-1 = 9
# 20-2 = 18
# 30-3 = 27
print(arr2-arr1)
#multiplication
# 10 *1 = 10
# 20*2 = 40
# 30*3=90
print(arr1*arr2)
# #division
# 10/1 = 10
# 20/2 = 10
# 30/3 = 10
print(arr2/arr1)
print(arr2//arr1)
print(arr2%arr1)
print(arr1**2)

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]
[10 10 10]
[0 0 0]
[1 4 9]


In [43]:
# Aggregate Functions :Functions used to summarize data.
l = np.array([10,20,20,40,50,60])
#add all elements = sum
print(np.sum(l))
#average
print(np.mean(l))
#minimum
print(np.min(l))
#maximum value
print(np.max(l))
#standard deviation
print(np.std(l))
#variance
print(np.var(l))
#size of elememts in an array
print(np.size(l))
#argmax : gives the index position of the largest value
print(np.argmax(l))
#argmin # it gives the index position of the minimum value
print(np.argmin(l))
#applying square root
print(np.sqrt(l))

200
33.333333333333336
10
60
17.950549357115012
322.22222222222223
6
5
0
[3.16227766 4.47213595 4.47213595 6.32455532 7.07106781 7.74596669]


In [44]:
arr = np.array([-1,-2,-3,-4,-5])
print(np.abs(arr)) #absolute function converts negative to positive

[1 2 3 4 5]


In [45]:
#numpy rounding functions
arr = np.array([1.2,2.7,3.5,4.1,5.9])
#round : round values to nearest integer
# 1.2 -> 1
# 2.7 -> 3
# 2.7 ->3
# 3.5 -> 4
# 4.1 -> 4
# 5.9->6
print(np.round(arr))


[1. 3. 4. 4. 6.]


In [46]:
arr = np.array([1.2,2.7,3.5,4.1,5.9])
#floor- it will always gives lower integer values
# 1.2 -> 1
# 2.7 > 2
# 3.5>3
# 4.1>4
# 5.9 >5
print(np.floor(arr))

[1. 2. 3. 4. 5.]


In [47]:
# ceil : it always gives upper inetger values
arr = np.array([1.2,2.7,3.5,4.1,5.9])
# 1.2 > 2
# 2.7 > 3
# 3.5 > 4
# 4.1>5
# 5.9>6

print(np.ceil(arr))

[2. 3. 4. 5. 6.]
